version: "3.8"

services:
  postgres-dev:
    container_name: dev-db
    image: postgres:15
    environment:
      - "POSTGRES_PASSWORD=serenade"
      - "POSTGRES_USER=serenade"
      - "POSTGRES_DB=serenade"
    volumes:
      - "./database:/docker-entrypoint-initdb.d"
    ports:
      - 5432:5432

  postgres-test:
    container_name: test-db
    image: postgres:15
    restart: always
    environment:
      - "POSTGRES_PASSWORD=tester"
      - "POSTGRES_USER=tester"
      - "POSTGRES_DB=serenade"
    volumes:
      - "./database:/docker-entrypoint-initdb.d"
    ports:
      - 5431:5432
